version: '3'

services: 
  nut_cracker:
    build: .
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9512:80"
    networks: 
      - nut_cracker

networks:
  nut_cracker:
    driver: overlay